### ISSUE TITLE
Is chat using embeddings?

### ISSUE THREAD

**Issue by MadBomber** [nickthecook/archyve#107]
I have one collection with one PDF document which was nicely chunked.  From documents I can enter a prompt and get back checnks that are clearly related to my prompt; however, when I go to chat, the response I get to that same query that I entered in the document search results in nothing from my document.  It is as if there was no embedding.  Is that the intended behavior or have I missed a configuration setting somewhere?

**Comment by nickthecook** [comment]
Hey @MadBomber, at the top of the chat page is the "Seach Collections" toggle on?

If so, perhaps the relevance score for the chunks is not high enough to be included. When you search in the Collections view, it will show you a fixed number of matching hits, sorted by relevance. The hits that are relevant enough to be included in chat context will have white text, but the ones that are not relevant enough will be greyed out a bit. This is so that, as an administrator of Archyve, you can see what the current settings would exclude, in case you want to tweak your settings to include more.

When you search Collections, do the hits look greyed out?

**Comment by MadBomber** [comment]
Thank you! It was the search collections switch.  My poor eyesight did not recognize it as an actionable element.  I saw it as a label to the drop-down collections menu to its right.

w/r/t accessibility maybe a change to a checkbox or the addition of extra text to indicate the status of the slide switch would help.
